### ISSUE TITLE
NeuralNet compitabliy problem with sklearn's cross_val_score and RepeatedKfold

### ISSUE THREAD

**Issue by AhmadM-DL** [skorch-dev/skorch#728] opened 2020-12-10 16:13 UTC
Hello there,
I am using Skorch with Sklearn's `cross_val_score` and `RepeatedKfold`.
I am working using the typical Sklearn ML pipeline.

```python
net = NeuralNet(...)
cv = RepeatedKfold(...)
# ensure y is 2-dimensional
y = np.array(y).reshape(-1, 1)
reg= cross_val_score(net, X, y, cv=cv, ...) 
```

Sklearn is throwing the following error:

```sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. 
The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: The target data shouldn't be 1-dimensional but instead have 2 dimensions, 
with the second dimension having the same size as the number of regression targets (usually 1). 
Please reshape your target data to be 2-dimensional (e.g. y = y.reshape(-1, 1).
```
The error is actually thrown by NeuralNet `Fit` method which requires the target variable to be 2-dimensional.
The problem is my target variable is 2-dimensional!

After following the execution flow I found that `_fit_and_score`  in Sklearn [cross_validate](https://github.com/scikit-learn/scikit-learn/blob/c9677d6a7d42aa7162a4c448284b8db1cabde0b0/sklearn/model_selection/_validation.py#L449)
```python
    results = parallel(
        delayed(_fit_and_score)(
            clone(estimator), X, y, scorers, train, test, verbose, None,
            fit_params, return_train_score=return_train_score,
            return_times=True, return_estimator=return_estimator,
            error_score=error_score)
        for train, test in cv.split(X, y, groups))
```
is transforming the passed 2-dimensional target into 1.  Note that the function takes the split indices from 
`cv.split` as arguments.

Any workarounds?

**Comment by ottonemo** [comment] 2020-12-10 16:58
I cannot reproduce the behavior you describe.

`y.shape` is not reduced to one dimension when passed to the cross validation. Counter example:

```python
import numpy as np
import sklearn


class Foo(sklearn.base.BaseEstimator, sklearn.base.ClassifierMixin):
    def fit(self, X, y):
        print(X.shape, y.shape)
        return self

    def predict(self, X):
        return np.zeros((len(X),))


X = np.zeros((10, 2))
y = np.zeros((10, 1))

from sklearn.model_selection import cross_val_score
from sklearn.utils import indexable

model = Foo()

print(cross_val_score(model, X, y, cv=3))

X, y, groups = indexable(X, y, None)

print(X.shape, y.shape)
```

Neither in `fit` nor after `indexable` has the shape of `y` changed to one dimension (it remains `(10, 1)`).
Are you sure this is your problem? What scikit-learn version are you using?

**Comment by AhmadM-DL** [comment] 2020-12-10 18:33
You are right.
I double checked and indexable doesn't have this effect.
I will edit the question.

**Comment by AhmadM-DL** [comment] 2020-12-10 18:57
I resolved the problem by sub-classing `NeuralNetRegressor`
and unsqueezing the target before calling `fit`
```python
class patchNNregressor(skorch.NeuralNetRegressor):
  def __init__(...):
  ...
  def fit(self, X, y, **fit_params):
    #if y is one dimensional, force it to 2 dimensional
    if isinstance(y, np.ndarray) and y.ndim == 1:
      y = y.reshape(-1, 1)
    return super(patchNNregressor, self).fit(X, y, **fit_params) 
```

**Comment by BenjaminBossan** [comment] 2020-12-12 13:51
@AhmadM-DL I assume the issue is resolved and will close it for now. Feel free to re-open if that's not the case.

**Closed by BenjaminBossan** 2020-12-12 13:51 UTC
Labels: question
