### ISSUE TITLE
GridSearchCV AttributeError: 'tuple' object has no attribute 'to'

### ISSUE THREAD

**Issue by preisleistung** [skorch-dev/skorch#633] opened 2020-05-11 13:04 UTC
I want to use `GridSearchCV`. The first optimization works, the problem seems to be when it runs the second. In this case I get the error `AttributeError: 'tuple' object has no attribute 'to'` since I have a LSTM, the forward method returns 1 array and a tuple of array (the hidden states) so I modified the loss function in this way (following sklearn documentation):

```python
from sklearn.metrics import mean_squared_error, make_scorer
def my_custom_loss(y_true, y_pred):
    y, (h, c) = y_pred
    return mean_squared_error(y, y_true)
```
and then used this one as  score:

```python
    loss = make_scorer(my_custom_loss, greater_is_better=False)

    # Load toy regressor
    X_regr, y_regr = make_regression(1000, 20, n_informative=10, random_state=0)
    X_regr = X_regr.astype(np.float32)
    y_regr = y_regr.astype(np.float32) / 100
    y_regr = y_regr.reshape(-1, 1)
    ni = 20
    no = 1
    nh = 10
    nlayers = 3
    net_regr = NeuralNetRegressor(
        module=MyLSTM,
        module__ni=ni,
        module__no=no,
        module__nh=nh,
        module__nlayers=nlayers,
        max_epochs=20,
        lr=0.1,
        criterion=ContextlessMSE,
        iterator_train__shuffle=True,  # this shuffles the training data
        #     device='cuda',  # uncomment this to train with CUDA
    )

    params = {
        'lr': [0.1, 0.2],
        'max_epochs': [10, 20],
        'module__nh': [10, 20],
    }
    gs = GridSearchCV(net_regr, params, refit=False, cv=2, scoring=loss)

    gs.fit(X_regr, y_regr)
    print(gs.best_score_, gs.best_params_)
```

where my net is
```python
class MyLSTM(nn.Module):
    def __init__(self, ni=6, no=3, nh=10, nlayers=1):
        super(MyLSTM, self).__init__()

        self.ni = ni
        self.no = no
        self.nh = nh
        self.nlayers = nlayers

        self.lstms = nn.ModuleList(
            [nn.LSTMCell(self.ni, self.nh)] + [nn.LSTMCell(self.nh, self.nh) for i in range(nlayers - 1)])
        self.out = nn.Linear(self.nh, self.no)
        self.do = nn.Dropout(p=0.2)
        self.actfn = nn.Tanh()
        self.device = torch.device('cpu')
        self.dtype = torch.float

    # description of the whole block
    def forward(self, x, h0=None, train=False):
        hs = x  # initiate hidden state
        if h0 is None:
            h = torch.zeros(hs.shape[0], self.nh, device=self.device)
            c = torch.zeros(hs.shape[0], self.nh, device=self.device)
        else:
            (h, c) = h0
        # LSTM cells
        for i in range(self.nlayers):
            h, c = self.lstms[i](hs, (h, c))
            hs = self.do(h)
            # Output layer
            y = self.out(hs)
            return y, (h, c)
```

but I still get the same error `AttributeError: 'tuple' object has no attribute 'to'`. I also wrote score=None, this is supposed to take the criterion of the net_regr, but I get the same error.

EDIT:
Here is the trace:

```
  epoch    train_loss    valid_loss     dur
-------  ------------  ------------  ------
      1        4.7059        4.6764  0.3500
      2        4.6389        4.7132  0.0440
      3        4.6186        4.7013  0.0480
      4        4.6165        4.6791  0.0380
      5        4.5922        4.6779  0.0440
      6        4.5839        4.6803  0.0470
      7        4.5791        4.6435  0.0570
      8        4.5341        4.6034  0.0460
      9        4.4922        4.5672  0.0510
     10        4.4390        4.5184  0.0480
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/morabru01/Desktop/WORKSPACE/Learning/testbenches/test_LSTM_skorch.py", line 120, in <module>
    test_gridsearch()
  File "C:/Users/morabru01/Desktop/WORKSPACE/Learning/testbenches/test_LSTM_skorch.py", line 115, in test_gridsearch
    gs.fit(X_regr, y_regr)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\sklearn\model_selection\_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\sklearn\model_selection\_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\sklearn\model_selection\_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\joblib\parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\joblib\parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\joblib\parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\joblib\_parallel_backends.py", line 209, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\joblib\_parallel_backends.py", line 590, in __init__
    self.results = batch()
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\joblib\parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\joblib\parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 544, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 591, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 89, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\sklearn\metrics\_scorer.py", line 371, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\sklearn\base.py", line 422, in score
    y_pred = self.predict(X)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\skorch\net.py", line 1069, in predict
    return self.predict_proba(X)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\skorch\net.py", line 1033, in predict_proba
    for yp in self.forward_iter(X, training=False):
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\skorch\net.py", line 920, in forward_iter
    yield to_device(yp, device=device)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\skorch\utils.py", line 151, in to_device
    return tuple(x.to(device) for x in X)
  File "C:\Users\morabru01\Desktop\WORKSPACE\Learning\venv\lib\site-packages\skorch\utils.py", line 151, in <genexpr>
    return tuple(x.to(device) for x in X)
AttributeError: 'tuple' object has no attribute 'to'

```

**Comment by ottonemo** [comment] 2020-05-11 16:40
Where does this error occur? You didn't supply a stack trace and I don't see the error immediately.

One thing I noticed, though: you shouldn't need to unpack the probabilities from the net instance in your scorer, skorch is doing that for you (see `predict()` and `predict_proba`, both methods take the first element if a tuple is returned by the module).

**Comment by preisleistung** [comment] 2020-05-12 07:26
Sorry I forgot the trace, now it's there.
Note that the first optimization works, the problem is the second one.

> One thing I noticed, though: you shouldn't need to unpack the probabilities from the net instance in your scorer, skorch is doing that for you (see predict() and predict_proba, both methods take the first element if a tuple is returned by the module).

ok got it :)

**Comment by ottonemo** [comment] 2020-05-12 10:07
Ah yes, now I see it. This is something that the documentation of `predict` is currently lacking but the documentation of `NeuralNet.forward` (which `predict` is based upon):

        The outputs from ``self.module_.forward`` are gathered on the
        compute device specified by ``device`` and then concatenated
        using PyTorch :func:`~torch.cat`. If multiple outputs are
        returned by ``self.module_.forward``, each one of them must be
        able to be concatenated this way.

You are returning torch tensors *and* tuples and the latter cannot be concatenated using torch tensor operations.

Change the return in your module to

```python
            return y, h, c
```

and everything should work as expected.

**Comment by preisleistung** [comment] 2020-05-12 11:08
thanks it works :). 

> You are returning torch tensors and tuples and the latter cannot be concatenated using torch tensor operations.

Why does this happen when GridSearchCV is used while I don't have any problem running the module as it is?

**Comment by ottonemo** [comment] 2020-05-12 15:46
> Why does this happen when GridSearchCV is used while I don't have any problem running the module as it is?

This is a very good question. The answer is due to caching. skorch scoring callbacks cache the network's output for each batch and temporarily overwrites `net.forward_iter` to return the cached results. Therefore the concatenation code is never actually executed. If you disable caching on the scoring callbacks you would see the same error during training as well.

**Comment by BenjaminBossan** [comment] 2020-06-06 18:45
It seems the issue is solved. I'll close it, feel free to re-open in case it's not resolved.

**Closed by BenjaminBossan** 2020-06-06 18:45 UTC
Labels: question
