### ISSUE TITLE
NeuralNetRegressor fit Error issue

### ISSUE THREAD

**Issue by quant-science** [skorch-dev/skorch#708] opened 2020-10-10 02:45 UTC
class RegressorModule(nn.Module):
     xxx

X_train, X_test, y_train, y_test = train_test_split(X_regr, y_regr)
valid_ds = Dataset(X_test, y_test)
net_regr = NeuralNetRegressor(
    module=RegressorModule,
    module__input_units = 20,
    criterion=torch.nn.MSELoss, 
    optimizer__lr = 0.01,
    iterator_train__shuffle = True,
    batch_size=128,
    max_epochs=50,
    train_split=predefined_split(valid_ds)
)
net_regr.fit(X_train, y_train)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-241-f5871c67147b> in <module>()
     40 
     41 
---> 42 net_regr.fit(X_train, y_train)
TypeError: _make_split() got multiple values for argument 'valid_ds'

Is there any hint to solve this error? thanks

**Comment by BenjaminBossan** [comment] 2020-10-10 14:33
Could you check if the error you get is the same as [this one](https://github.com/skorch-dev/skorch/issues/681)? If so, it should be fixed right now by #682, which is part of the latest skorch release (version 0.9.0). So please check your skorch version:

`$ python -c 'import skorch;print(skorch.__version__)'`

If you're on an older version and installed skorch via pip, `$ pip install -U skorch` should do the trick.

**Comment by quant-science** [comment] 2020-10-11 00:18
@BenjaminBossan yes, exactlly the same error. skorch package is the latest version. btw, I tried to use validation dataset of pytorch DataSet  format, but failed

**Comment by BenjaminBossan** [comment] 2020-10-12 21:17
I tried to reproduce your error but was unsuccessful. Since your example is not complete, I had to add some changes though. Could please try out this code?

```python
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from skorch.dataset import Dataset
from skorch.helper import predefined_split
from skorch import NeuralNetRegressor
from skorch.toy import make_regressor
import torch

X_regr, y_regr = make_regression(1000, 20)
X_regr, y_regr = X_regr.astype(np.float32), y_regr.astype(np.float32)
X_train, X_test, y_train, y_test = train_test_split(X_regr, y_regr)
valid_ds = Dataset(X_test, y_test)

net_regr = NeuralNetRegressor(
    module=make_regressor(),
    module__input_units=20,
    criterion=torch.nn.MSELoss,
    optimizer__lr=0.01,
    iterator_train__shuffle=True,
    batch_size=128,
    max_epochs=50,
    train_split=predefined_split(valid_ds)
)
net_regr.fit(X_train, y_train.reshape(-1, 1))
```

**Comment by quant-science** [comment] 2020-10-14 15:38
@BenjaminBossan  sorry for the late response. 
I tried your code, still the  `TypeError: _make_split() got multiple values for argument 'valid_ds'`
skorch version 0.9.0 on Win10

**Comment by BenjaminBossan** [comment] 2020-10-14 17:23
That's strange. Could you please:

1. Create a new env and install skorch from master, then test again
2. Paste the full stacktrace

My suspicion is that somehow still the old code is being used.

**Comment by JustasB** [comment] 2020-11-18 19:44
Hi @BenjaminBossan , 

I get the same error message using the same code as in https://github.com/skorch-dev/skorch/issues/708#issuecomment-707350338

`print(skorch.__version__)` yields `0.9.0`
`print(torch.__version__)` yields `1.6.0`

The full stack trace is:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-a2db0ba30800> in <module>
     24     train_split=predefined_split(valid_ds)
     25 )
---> 26 net_regr.fit(X_train, y_train.reshape(-1, 1))

~/miniconda3/lib/python3.7/site-packages/skorch/regressor.py in fit(self, X, y, **fit_params)
     89         # this is actually a pylint bug:
     90         # https://github.com/PyCQA/pylint/issues/1085
---> 91         return super(NeuralNetRegressor, self).fit(X, y, **fit_params)

~/miniconda3/lib/python3.7/site-packages/skorch/net.py in fit(self, X, y, **fit_params)
    901             self.initialize()
    902 
--> 903         self.partial_fit(X, y, **fit_params)
    904         return self
    905 

~/miniconda3/lib/python3.7/site-packages/skorch/net.py in partial_fit(self, X, y, classes, **fit_params)
    860         self.notify('on_train_begin', X=X, y=y)
    861         try:
--> 862             self.fit_loop(X, y, **fit_params)
    863         except KeyboardInterrupt:
    864             pass

~/miniconda3/lib/python3.7/site-packages/skorch/net.py in fit_loop(self, X, y, epochs, **fit_params)
    764 
    765         dataset_train, dataset_valid = self.get_split_datasets(
--> 766             X, y, **fit_params)
    767         on_epoch_kwargs = {
    768             'dataset_train': dataset_train,

~/miniconda3/lib/python3.7/site-packages/skorch/net.py in get_split_datasets(self, X, y, **fit_params)
   1300             return self.train_split(dataset, **fit_params)
   1301 
-> 1302         return self.train_split(dataset, y, **fit_params)
   1303 
   1304     def get_iterator(self, dataset, training=False):

TypeError: _make_split() got multiple values for argument 'valid_ds'
```

**Comment by BenjaminBossan** [comment] 2020-11-18 23:42
Thanks for reporting. Again, it seems like this is code from before the bugfix in #682. You could really help me by going inside `~/miniconda3/lib/python3.7/site-packages/skorch/utils.py` and pasting the code from the function `_make_split` (should be line 494-496).

**Comment by JustasB** [comment] 2020-11-19 12:02
I hear you, it's a weird one. This is what `_make_split` looks like:

```
def _make_split(X, valid_ds, **kwargs):
    """Used by ``predefined_split`` to allow for pickling"""
    return X, valid_ds
```

I see the same function body by opening the file directly or using this:

```
import inspect
lines = inspect.getsource(skorch.utils._make_split)
print(lines)
```

As a workaround, I found that placing the following lines above [the example](https://github.com/skorch-dev/skorch/issues/708#issuecomment-707350338) (and restarting the kernel), allows training to proceed (basically replacing `valid_ds` param with `*args`):

```
def _make_split(X, *args, **kwargs):
    """Used by ``predefined_split`` to allow for pickling"""
    return X, valid_ds

import skorch
skorch.utils._make_split = _make_split
```

I don't know the skorch internals well enough to know if that would work in all use-cases, though.

**Comment by BenjaminBossan** [comment] 2020-11-19 23:21
> Is it possible that an old version of utils.py is somehow getting uploaded to pipy?

Yes, that's indeed the case, I just installed from pypi. Not sure what happened there.

For the time being, it's probably best to install skorch from master until we make our next release, which should hopefully work as intended.

**Comment by BenjaminBossan** [comment] 2020-12-29 15:01
I think nothing needs to be added here, thus will close the issue.

**Closed by BenjaminBossan** 2020-12-29 15:01 UTC
Labels: question
