### ISSUE TITLE
Error message when gridSearch with y=None:  TypeError: fit() missing 1 required positional argument: 'y'

### ISSUE THREAD

**Issue by xiaolongwu0713** [skorch-dev/skorch#766] opened 2021-04-29 19:07 UTC
Hi, I am doing grid search with Skorch. Before the grid search I just do regular fit with Skorch and no error or warning msg. However when I am add grid search I got below error msg:

```
gs = GridSearchCV(net, params, refit=False, cv=5, scoring='neg_mean_squared_error', verbose=2) # score: higher is better
gs.fit(train_and_val_ds,y=None)

Fitting 5 folds for each of 3600 candidates, totalling 18000 fits
[CV] lr=0.001, module__dropout=0.1, module__num_S=2, module__num_T=2, optimizer=<class 'torch.optim.adam.Adam'>, optimizer__weight_decay=0 
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
TypeError: fit() missing 1 required positional argument: 'y'

  FitFailedWarning)
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   28.2s remaining:    0.0s
[CV]  lr=0.001, module__dropout=0.1, module__num_S=2, module__num_T=2, optimizer=<class 'torch.optim.adam.Adam'>, optimizer__weight_decay=0, total=  22.7s
[CV] lr=0.001, module__dropout=0.1, module__num_S=2, module__num_T=2, optimizer=<class 'torch.optim.adam.Adam'>, optimizer__weight_decay=0 
[CV]  lr=0.001, module__dropout=0.1, module__num_S=2, module__num_T=2, optimizer=<class 'torch.optim.adam.Adam'>, optimizer__weight_decay=0, total=  16.7s
[CV] lr=0.001, module__dropout=0.1, module__num_S=2, module__num_T=2, optimizer=<class 'torch.optim.adam.Adam'>, optimizer__weight_decay=0 
```
The fitting is still going even through the error msg. Should I concern about this error msg? (I have my training and label in the same dataset, so I set y=none.)

**Comment by xiaolongwu0713** [comment] 2021-04-29 20:33
Here is the full log of less parameter. Very strange the program continues even where is an error message.

```
net = MyRegressor(
    module__num_S=num_ST,
    module__dropout=dropout,
    iterator_train__shuffle=True,
    train_split=None, # grid search
    verbose=0, # grid search
    max_epochs=100,
    lr=learning_rate,
    batch_size=1,
    optimizer=torch.optim.Adam,
    criterion = nn.MSELoss,
    callbacks=[('plotPrediction', plotPrediction(result_dir)),cp,train_end_cp], # early_stopping_callbacks
    device = device
)

params = {
    'lr': [0.001, 0.003],
    'module__num_S':[2,3],
}


Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] lr=0.001, module__num_S=2 .......................................
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
TypeError: fit() missing 1 required positional argument: 'y'

  FitFailedWarning)
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   24.6s remaining:    0.0s
[CV] ........................ lr=0.001, module__num_S=2, total=  19.2s
[CV] lr=0.001, module__num_S=2 .......................................
[CV] ........................ lr=0.001, module__num_S=2, total=  14.1s
[CV] lr=0.001, module__num_S=2 .......................................
[CV] ........................ lr=0.001, module__num_S=2, total=  14.1s
[CV] lr=0.001, module__num_S=2 .......................................
[CV] ........................ lr=0.001, module__num_S=2, total=  14.1s
[CV] lr=0.001, module__num_S=2 .......................................
[CV] ........................ lr=0.001, module__num_S=2, total=  14.1s
[CV] lr=0.001, module__num_S=3 .......................................
[CV] ........................ lr=0.001, module__num_S=3, total=  14.1s
[CV] lr=0.001, module__num_S=3 .......................................
[CV] ........................ lr=0.001, module__num_S=3, total=  14.1s
[CV] lr=0.001, module__num_S=3 .......................................
[CV] ........................ lr=0.001, module__num_S=3, total=  14.2s
[CV] lr=0.001, module__num_S=3 .......................................
[CV] ........................ lr=0.001, module__num_S=3, total=  14.1s
[CV] lr=0.001, module__num_S=3 .......................................
[CV] ........................ lr=0.001, module__num_S=3, total=  14.0s
[CV] lr=0.003, module__num_S=2 .......................................
[CV] ........................ lr=0.003, module__num_S=2, total=  14.1s
[CV] lr=0.003, module__num_S=2 .......................................
[CV] ........................ lr=0.003, module__num_S=2, total=  14.1s
[CV] lr=0.003, module__num_S=2 .......................................
[CV] ........................ lr=0.003, module__num_S=2, total=  14.2s
[CV] lr=0.003, module__num_S=2 .......................................
[CV] ........................ lr=0.003, module__num_S=2, total=  14.1s
[CV] lr=0.003, module__num_S=2 .......................................
[CV] ........................ lr=0.003, module__num_S=2, total=  14.1s
[CV] lr=0.003, module__num_S=3 .......................................
[CV] ........................ lr=0.003, module__num_S=3, total=  14.1s
[CV] lr=0.003, module__num_S=3 .......................................
[CV] ........................ lr=0.003, module__num_S=3, total=  14.1s
[CV] lr=0.003, module__num_S=3 .......................................
[CV] ........................ lr=0.003, module__num_S=3, total=  14.1s
[CV] lr=0.003, module__num_S=3 .......................................
[CV] ........................ lr=0.003, module__num_S=3, total=  14.1s
[CV] lr=0.003, module__num_S=3 .......................................
[CV] ........................ lr=0.003, module__num_S=3, total=  14.1s
[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:  4.9min finished
GridSearchCV(cv=5, error_score=nan,
             estimator=<class 'grasp.myskorch.MyRegressor'>[uninitialized](
  module=<class 'grasp.TSception.Models.TSception2'>,
  module__batch_size=280,
  module__chnNum=114,
  module__dropout=0.5,
  module__num_S=3,
  module__num_T=3,
  module__sampling_rate=1000,
  module__step=50,
  module__wind_size=1000,
),
             iid='deprecated', n_jobs=None,
             param_grid={'lr': [0.001, 0.003], 'module__num_S': [2, 3]},
             pre_dispatch='2*n_jobs', refit=False, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=2)
```

Another thing I don't understand is why I can't see any epoch information in the output?  You can see here each CV lasts 14s, does these 100(max_epochs) epochs completed within each 14s? That's nearly impossible because I have a very large training dataset. Normally it will take 3mins to finish one epoch.

Could you please explain?

**Comment by xiaolongwu0713** [comment] 2021-04-29 20:37
I tried the max_epochs=1000, it has no effect on the whole training process at all.

**Comment by xiaolongwu0713** [comment] 2021-04-30 12:45
I just pick up some info in the doc:  https://skorch.readthedocs.io/en/stable/user/FAQ.html#how-do-i-use-sklearn-gridseachcv-when-my-data-is-in-a-dataset. I assume above strange behavior is caused by my input being dataset?

**Comment by BenjaminBossan** [comment] 2021-04-30 13:06
> Very strange the program continues even where is an error message.

This is a change in sklearn's grid search: It will continue, even if there is an error. The reason is so that if a single parameter causes the problem, not the whole grid search is canceled. In this case, however, all fits are affected and in the end, you will have no results.

> I assume above strange behavior is caused by my input being dataset?

Yes, please try the solution shown in the [docs](https://skorch.readthedocs.io/en/stable/user/helper.html#slicedataset) and report back if it works. The problem is that sklearn itself always expects there to be a `y`.

**Comment by xiaolongwu0713** [comment] 2021-04-30 19:06
Hi Ben, I still can't get it running.
This is my net definition:

```
net = MyRegressor(
    module=TSception2,
    module__wind_size=T,
    module__step=step,
    module__sampling_rate=sampling_rate,
    module__chnNum=chnNum,
    module__num_T=num_ST,
    module__num_S=num_ST,
    module__batch_size=batch_size,
    module__dropout=dropout,
    lambda1=Lambda,
    iterator_train__shuffle=True,
    verbose=0, # grid search
    max_epochs=10,
    lr=learning_rate,
    batch_size=1,
    optimizer=torch.optim.Adam,
    criterion = nn.MSELoss,
    callbacks=[('plotPrediction', plotPrediction(result_dir)),cp,train_end_cp], # early_stopping_callbacks
    device = device
)
```
Here is my dataset. 
```
class SEEGDataset(Dataset):

    def __init__(self, x_tensor, y_tensor, T, step):
        self.x = x_tensor
        self.y = y_tensor
        self.chnNum=x_tensor.shape[1]
        self.T=T
        self.step=step
        self.totalLen = x_tensor.shape[2]  # ms
        self.batch_size = int((self.totalLen - T) / step)  # 280
        assert self.x.shape[0] == self.y.shape[0]
    def __getitem__(self, index):
        trainx=self.x[index]
        trainy=self.y[index]
        x = np.zeros((self.batch_size, 1, self.chnNum, self.T))  # 4D:(280,1,19,1000ms):(batch_size, planes, height, weight)
        y = np.zeros((self.batch_size, 1))  # (280, 1)
        yd = np.zeros((self.batch_size, 1))  # (280, 1)
        for bs in range(self.batch_size):
            x[bs, 0, :, :] = trainx[:, bs*self.step:(bs*self.step + self.T)]
            y[bs, 0] = trainy[bs * self.step + self.T + 1] # force
            yd[bs,0] = abs(trainy[bs*self.step + self.T +1] - trainy[bs*self.step + self.T -50])*10+0.05 # force derative
        yd[:,0] = [abs(item) / 5 if abs(item) > 0.2 else abs(item) for item in yd[:,0]]

        return x.astype(np.float32),y.astype(np.float32) # x shape: ([28, 1, 110, 1000]), y shape: ([28, 1])
        #return x.astype(np.float32), np.expand_dims(y, axis=1).astype(np.float32)

    def __len__(self):
        return self.y.shape[0]

```
Some sanity check on my SliceDataset:
```
train_and_val_ds = SEEGDataset(train_and_valx, train_and_valy,T, step)
X_sl = SliceDataset(train_and_val_ds, idx=0)  # idx=0 is the default
y_sl = SliceDataset(train_and_val_ds, idx=1)
X_sl.shape retrun: (10,)
y_sl.shape retrun: (10,)
a=X_sl[0]
a.shape returns: (280, 1, 90, 1000) # Each item in the dataset is already a batch with batch_size=280.
b=y_sl[0]
b.shape returns: (280, 1) # The same 280 batch_size in y.

```

If I run gs.fit(X_sl,y_sl), I will have error below:

```
gs.fit(X_sl,y_sl)
Fitting 5 folds for each of 2 candidates, totalling 10 fits
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[CV] lr=0.001 ........................................................
/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
[CV] ......................................... lr=0.001, total=   0.0s
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/skorch/regressor.py", line 91, in fit
    return super(NeuralNetRegressor, self).fit(X, y, **fit_params)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/skorch/net.py", line 917, in fit
    self.partial_fit(X, y, **fit_params)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/skorch/net.py", line 876, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/skorch/net.py", line 776, in fit_loop
    self.check_data(X, y)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/skorch/regressor.py", line 76, in check_data
    raise ValueError(msg)
ValueError: The target data shouldn't be 1-dimensional but instead have 2 dimensions, with the second dimension having the same size as the number of regression targets (usually 1). Please reshape your target data to be 2-dimensional (e.g. y = y.reshape(-1, 1).

```
So I replace the return statement in my dataset class with below return to convert add extra dimension:
`return x.astype(np.float32), np.expand_dims(y, axis=1).astype(np.float32) `
Then the error msg is gone, but the network didn't training anything, as you can see the time elapse is 0s:

```
gs.fit(X_sl,y_sl)
Fitting 5 folds for each of 2 candidates, totalling 10 fits
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[CV] lr=0.001 ........................................................
[CV] ......................................... lr=0.001, total=   0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[CV] lr=0.001 ........................................................
[CV] ......................................... lr=0.001, total=   0.0s
[CV] lr=0.001 ........................................................
[CV] ......................................... lr=0.001, total=   0.0s
[CV] lr=0.001 ........................................................
[CV] ......................................... lr=0.001, total=   0.0s
[CV] lr=0.001 ........................................................
[CV] ......................................... lr=0.001, total=   0.0s
[CV] lr=0.003 ........................................................
[CV] ......................................... lr=0.003, total=   0.0s
[CV] lr=0.003 ........................................................
[CV] ......................................... lr=0.003, total=   0.0s
[CV] lr=0.003 ........................................................
[CV] ......................................... lr=0.003, total=   0.0s
[CV] lr=0.003 ........................................................
[CV] ......................................... lr=0.003, total=   0.0s
[CV] lr=0.003 ........................................................
[CV] ......................................... lr=0.003, total=   0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.2s finished
Out[57]: 
GridSearchCV(cv=5,
             estimator=<class 'grasp.myskorch.MyRegressor'>[uninitialized](
  module=<class 'grasp.TSception.Models.TSception2'>,
  module__batch_size=280,
  module__chnNum=90,
  module__dropout=0.5,
  module__num_S=3,
  module__num_T=3,
  module__sampling_rate=1000,
  module__step=50,
  module__wind_size=1000,
),
             param_grid={'lr': [0.001, 0.003]}, refit=False,
             scoring='neg_mean_squared_error', verbose=2)
```

Note that my batch_size=1. The data flow is like this: I read one element each time from my dataset. Then inside my nn.Module, this one element have a dimension of (280,1,length, width) for x and (280,1) for y. The 280 is the actual batch size in the point view of nn.Module.

**Comment by xiaolongwu0713** [comment] 2021-04-30 20:26
I tried to use numpy, but it just keep crashing on the memory usage.

**Comment by BenjaminBossan** [comment] 2021-05-02 16:16
> Then the error msg is gone, but the network didn't training anything, as you can see the time elapse is 0s:

Okay, this is strange. Could you please use the same dataset without grid search and see if the net is training at all? If you turned off verbosity of the net, please turn it on again.

Honestly, your dataset definition looks pretty complicated, therefore I don't understand everything that's going on there. Also remember that the transformations within `__getitem__` are performed once per epoch, thus can be very expensive. Would it not be possible for you to instead do this transformation a single time, before putting the data inside a dataset? Just let the data be a numpy array or torch tensor and use the default dataset instead. I don't see why that shouldn't be possible, memory doesn't look like an issue.

**Comment by BenjaminBossan** [comment] 2021-06-06 18:45
@xiaolongwu0713 Any updates?

**Comment by QuanhanSun** [comment] 2021-06-10 05:51
l also met same problem with numpy, it just keep crashing on the memory usage. When l change my array into torch.tensor, it works well with net.fit()

> I tried to use numpy, but it just keep crashing on the memory usage.

**Comment by BenjaminBossan** [comment] 2021-06-12 14:15
@QuanhanSun That's interesting, it doesn't sound like that should happen. Could you please provide some code so that I can look into it?

**Comment by QuanhanSun** [comment] 2021-06-15 01:40
@BenjaminBossan Here is my code to reproduce the problem.
load the dataset
```
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import optuna

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error as mae

data = pd.read_csv('data_airline-passengers.csv')

sc = MinMaxScaler()
sc.fit(data[['Passengers']])
data['Passengers'] = sc.transform(data[['Passengers']].astype(np.float))

train_size = int(0.67 * len(data))
data_train = data[:train_size]
data_test = data[train_size:]
```

 Use torch dataset to deal with the data
```
class TimeSeriesTensor(UserDict):
    def __init__(self,
                 dataset: pd.DataFrame,
                 target: str,
                 tensor_structure: dict,
                 timestamp: str = None,
                 index: str = None,
                 H: int = 1,
                 freq: str = 'D',
                 drop_incomplete=True,
                 batch_first=True) -> None:

        super(TimeSeriesTensor, self).__init__()
        self.dataset = dataset
        self.target = target
        self.timestamp = timestamp
        self.tensor_structure = tensor_structure
        self.tensor_names = list(tensor_structure.keys())
        self.batch_first = batch_first

        # 预处理数据
        if timestamp is not None:
            self.dataset.loc[:, timestamp] = pd.to_datetime(self.dataset[timestamp])
            self.dataset = self.dataset.set_index(timestamp)
        self.dataset = self.dataset.sort_index()

        dataframe_list = []
        if index is None:
            # 区分index
            sub_df = self.dataset.copy()
            sub_dataframe = self._shift_data(sub_df, H, freq, drop_incomplete)
            dataframe_list.append(sub_dataframe)
        else:
            # 多个index来处理
            self.n_timeseries = self.dataset[index].nunique(dropna=True)
            self.indexs = self.dataset[index].unique()
            assert len(self.indexs) == self.n_timeseries, f'{index}列数据中有nan'
            for id in tqdm(self.indexs):
                sub_df = self.dataset[self.dataset[index] == id]
                sub_dataframe = self._shift_data(sub_df, H, freq, drop_incomplete)
                dataframe_list.append(sub_dataframe)

        # 按照不同的时序曲线分别去整理数据然后归并
        self.dataframe = pd.concat(dataframe_list, axis=0)
        self.data = self._df2tensors(self.dataframe)

    def _shift_data(self, dataset, H, freq, drop_incomplete):
        df = dataset.copy()
        idx_tuples = []
        for t in range(1, H + 1):
            df['t+' + str(t)] = df[self.target].shift(t * -1, freq=freq)
            idx_tuples.append(('target', 'y', 't+' + str(t)))

        for name, structure in self.tensor_structure.items():
            rng = structure[0]
            dataset_cols = structure[1]
            for col in dataset_cols:
                # do not shift non-sequential 'static' features
                if rng is None:
                    df['context_' + col] = df[col]
                    idx_tuples.append((name, col, 'static'))

                else:
                    for t in rng:
                        sign = '+' if t > 0 else ''
                        shift = str(t) if t != 0 else ''
                        period = 't' + sign + shift
                        shifted_col = name + '_' + col + '_' + period
                        df[shifted_col] = df[col].shift(t * -1, freq=freq)
                        idx_tuples.append((name, col, period))

        df = df.drop(self.dataset.columns, axis=1)
        idx = pd.MultiIndex.from_tuples(idx_tuples, names=['tensor', 'feature',
                                                           'time step'])
        df.columns = idx

        if drop_incomplete:
            df = df.dropna(how='any')

        return df

    def _df2tensors(self, dataframe):

        inputs = {}
        y = dataframe['target']
        y = y.values
        inputs['target'] = y

        for name, structure in self.tensor_structure.items():
            rng = structure[0]
            cols = structure[1]
            tensor = dataframe[name][cols].values
            if rng is None:
                tensor = tensor.reshape(tensor.shape[0], len(cols))
            else:
                tensor = tensor.reshape(tensor.shape[0], len(cols), len(rng))
                if self.batch_first:
                    tensor = np.transpose(tensor, axes=[0, 2, 1])
                else:
                    tensor = np.transpose(tensor, axes=[2, 0, 1])
            inputs[name] = tensor

        return inputs
```

```
class RNNDataset(Dataset):
    def __init__(self, tsdata: TimeSeriesTensor) -> None:
        self.tsdata = tsdata

        self.time_dependent_tensors = []
        for name, structure in self.tsdata.tensor_structure.items():
            rng = structure[0]
            if rng is not None:
                self.time_dependent_tensors.append(name)

        if len(self.time_dependent_tensors) > 1:
            self.data = np.concatenate(itemgetter(*self.time_dependent_tensors)(
                self.tsdata), axis=2).copy()
        else:
            self.data = self.tsdata[self.time_dependent_tensors[0]].copy()

    def __len__(self):
        return self.tsdata.dataframe.shape[0]

    def __getitem__(self, item):
        return self.data[item], self.tsdata['target'][item]
```

```
T = 8
HORIZON = 1
tensor_structure = {'X': (range(-T + 1, 1), ['Passengers'])}
tsdata = TimeSeriesTensor(data, 'Passengers', tensor_structure, timestamp='Month', H=HORIZON, freq='MS',
                          batch_first=True)

tsdata_train = TimeSeriesTensor(data_train, 'Passengers', tensor_structure, timestamp='Month', H=HORIZON, freq='MS',
                                batch_first=True)

tsdata_test = TimeSeriesTensor(data_test, 'Passengers', tensor_structure, timestamp='Month', H=HORIZON, freq='MS',
                               batch_first=True)

dataset_train = RNNDataset(tsdata_train)
dataset_test = RNNDataset(tsdata_test)

X_train = np.array([x for x, y in iter(dataset_train)])
Y_train = np.array([y for x, y in iter(dataset_train)])

# X_train = torch.from_numpy(X_train).float()
# Y_train = torch.from_numpy(Y_train).float() 
```
My lstm model
```
class LSTM(nn.Module):
    def __init__(self,
                 hidden_size: int,
                 num_layers: int,
                 input_size: int = 1,
                 output_size: int = 1):
        super(LSTM, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.output_size = output_size
        self.lstm = nn.LSTM(input_size=input_size,
                            hidden_size=hidden_size,
                            num_layers=num_layers,
                            batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x) -> torch.Tensor:
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).requires_grad_()
        c0 = torch.zeros_like(h0).requires_grad_()

        out, (_, _) = self.lstm(x, (h0.detach(), c0.detach()))
        res = self.fc(out[:, -1, :])

        return res

lstm_net = NeuralNetRegressor(module=LSTM(4,1,1,1))

```
Then run 
```
lstm_net.fit(X_trian, Y_train)
```

It will cause 
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

when l uncomment two line to change X_train , Y_train to torch tensor, it work well.
```
# X_train = torch.from_numpy(X_train).float()
# Y_train = torch.from_numpy(Y_train).float()
```
Hope l describe the problem clearly.
[data_airline-passengers.csv](https://github.com/skorch-dev/skorch/files/6652157/data_airline-passengers.csv)

**Comment by BenjaminBossan** [comment] 2021-06-16 20:47
@QuanhanSun Thanks for providing the code. I didn't understand everything that's happening, but I could make it run. The only modifications I made were:

1. convert `X_train` and `Y_train` dtype to float32: `X_train, Y_train = X_train.astype(np.float32), Y_train.astype(np.float32)`
2. make `RNNDataset` inherit from `torch.utils.data.Dataset` (it was not clear if it was a torch or skorch dataset)

After this, the code ran without problem and I couldn't detect any memory issues, in fact the memory used during training was so small that it barely made a difference overall.

Maybe that is because the linked csv only contains a small amount of the total data? Could you please confirm? If that is really all the data, I cannot explain why it would cause memory issues. From my understanding, signal 11 also doesn't mean that there was not enough memory but another memory issue.

Unrelated: At the beginning, you fit the `MinMaxScaler` on the whole dataset, before splitting into train and test. Unless you have a very specific reason not to, you should fit it only on the training data and then transform the test data.

**Comment by QuanhanSun** [comment] 2021-06-17 03:34
@BenjaminBossan Thanks for reply, it is a simply sample for me to test skorch before l use skorch in my work. Actually, skorch works well in the project except this strange example, l also spent some time to find out why ,but failed.  shy..

>  make RNNDataset inherit from torch.utils.data.Dataset (it was not clear if it was a torch or skorch dataset)

it is inherited from torch.utils.data.Dataset

> Unrelated: At the beginning, you fit the MinMaxScaler on the whole dataset, before splitting into train and test. Unless you have a very specific reason not to, you should fit it only on the training data and then transform the test data.

thanks for reminding, it just used for testing.

> Maybe that is because the linked csv only contains a small amount of the total data?
 
The csv is the total data. it is a small test csv.

**Comment by BenjaminBossan** [comment] 2021-06-17 21:33
Well, this is a really strange bug. Does it always occur at the same time or is it random? Could you try with the latest PyTorch version (1.9)?

**Comment by QuanhanSun** [comment] 2021-06-18 01:17
@BenjaminBossan  For this case, it always occur. My torch version is 1.6.0, l will check it later with version 1.9

> Well, this is a really strange bug. Does it always occur at the same time or is it random? Could you try with the latest PyTorch version (1.9)?

**Comment by BenjaminBossan** [comment] 2021-06-27 12:09
@QuanhanSun Did you have time to try it out?

**Comment by QuanhanSun** [comment] 2021-07-01 02:20
@BenjaminBossan l tried with torch 1.9.0+cu11.1, it will raise RuntimeError: expected scalar type Double but found Float. After l astype x_train y_train as np.float32, it workd well.

**Comment by BenjaminBossan** [comment] 2021-07-03 15:06
Okay, so it had something to do with PyTorch. I'll close the issue for now.

**Closed by BenjaminBossan** 2021-07-03 15:06 UTC
