### ISSUE TITLE
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment when deepcopying a model 

### ISSUE THREAD

**Issue by KhabbabZakaria** [skorch-dev/skorch#833] opened 2022-01-30 11:36 UTC
I am trying to deepcopy a model:
```
class Model(torch.nn.Module):
    def __init__(self, ann_private, rnn_public, policy):
        super(Model, self).__init__()
        self.ann_private = ann_private
        self.rnn_public = rnn_public
        self.policy = policy

    def forward(self, private_input, state):
      private_input = self.ann_private(private_input)
      processed_state = self.rnn_public(state)
      self.inference_state = torch.cat([processed_state, private_input], dim=-1)

      mu, sigma, state_values =  self.policy(self.inference_state)
      return mu, sigma, state_values

class Policy(nn.Module):
    """
    implements both actor and critic in one model
    """
    def __init__(self):
        super(Policy, self).__init__()
        self.fc1 = nn.Linear(state_size*2, 64)

        self.fc2 = nn.Linear(64, 32)
        self.layer_out = nn.Sequential(nn.Linear(32, 1), nn.Softmax(dim=-1))


        # actor's layer
        self.action_head = nn.Linear(state_size*2, 1)
        self.muHead = nn.Sigmoid()
        self.varHead = nn.Softplus()

        # critic's layer
        self.value_head = nn.Linear(state_size*2, 1)


    def forward(self, x):
        """
        forward of both actor and critic
        """
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.layer_out(x)
        x = torch.flatten(x)

        action_prob = self.action_head(x)
        self.mu = self.muHead(action_prob)
        var = self.varHead(action_prob)
        self.sigma = torch.sqrt(var)

        state_values = self.value_head(x)

        return self.mu, self.sigma, state_values
```
The policy contains some ‘self.mu’, ‘self.sigma’ etc (which are as I suppose causes of this problem, as before I was just calling them mu, sigma and deepcopy was working, but now I explicitly need self for them).
Any solution?

**Comment by BenjaminBossan** [comment] 2022-01-30 13:13
As far as I can tell, your problem is independent of skorch and occurs just by using `nn.Module`, right? Therefore, I'm not sure if I can help you here.

At a glance, I see that you store some forward outputs as attributes on the modules, e.g.:

> self.inference_state = torch.cat([processed_state, private_input], dim=-1)

> self.mu = self.muHead(action_prob)

> self.sigma = torch.sqrt(var)

Maybe the problem is related to that? Do you really need to store these outputs on the module? If not, try to remove the attributes and check if the problem still occurs. If it does, I'd suggest asking on the PyTorch forums.

**Comment by KhabbabZakaria** [comment] 2022-01-30 16:31
Yes that should be the case. I could not just omit the attributes as I needed to call them later, so I did a little cheat and could omit the attributes. Now deepcopy is working.

**Comment by BenjaminBossan** [comment] 2022-01-30 17:21
Fantastic. Maybe you could share your "little cheat" here for future readers.

Meanwhile, since it sounds like the problem was solved, I'll close the issue if you don't mind.

**Closed by BenjaminBossan** 2022-01-30 17:21 UTC
Labels: question

**Comment by KhabbabZakaria** [comment] 2022-01-30 18:04
Sure! So, instead of making mu, sigma attributes, I made the input of Policy an attribute (self.inference_state in the model). Then I called it to calculate mu,sigma which are the outputs of the Policy. So, just 
```
inference_state = model.inference_state
mu, sigma = policy(inference_state)
```
